# Generated by Django 4.0.5 on 2022-06-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_products',
            name='no_of_purchases',
        ),
        migrations.AddField(
            model_name='product',
            name='no_of_purchases',
            field=models.IntegerField(default=0),
        ),
    ]
