# Generated by Django 4.0.5 on 2022-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_invoice_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='product_color',
            field=models.CharField(max_length=15),
        ),
    ]
