# Generated by Django 4.0.5 on 2022-06-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_invoice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Cash On Delivery', max_length=30),
        ),
    ]
