# Generated by Django 4.0.5 on 2022-07-01 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_order_order_status_invoice_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pick_up_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pick_up_status',
            field=models.CharField(choices=[('Will Soon Pick Up the Product', 'Will Soon Pick Up the Product'), ('Pick Up Done', 'Pick Up Done')], default='Will Soon Pick Up the Product', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refund_status',
            field=models.CharField(choices=[('Not Initiated', 'Not Initiated'), ('Initiated', 'Initiated'), ('Done', 'Done')], default='Not Initiated', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replace_delivery_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='replace_delivery_status',
            field=models.CharField(choices=[('Not Packed', 'Not Packed'), ('Ready For Shipment', 'Ready For Shipment'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Not Packed', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replace_pickup_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='replace_pickup_status',
            field=models.CharField(choices=[('Will Soon Pick Up the Product', 'Will Soon Pick Up the Product'), ('Pick Up Done', 'Pick Up Done')], default='Will Soon Pick Up the Product', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replace_product_color',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replace_product_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replaced_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='replaced_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='replacement_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='returned_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='returned_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='returned_status',
            field=models.BooleanField(default=False),
        ),
    ]
