# Generated by Django 4.0.5 on 2022-07-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_invoice_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pick_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='replace_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='replace_pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='replaced_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
