# Generated by Django 4.0.5 on 2022-07-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_colour_size_alter_sub_products_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_products',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.colour'),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.size'),
        ),
    ]
