# Generated by Django 4.0.5 on 2022-07-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_sub_products_color_alter_sub_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_products',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('black', 'black')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='sub_products',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='XL', max_length=10),
        ),
    ]
