# Generated by Django 4.0.5 on 2022-07-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_invoice_returned_last_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='returned_last_date',
        ),
    ]
