# Generated by Django 4.0.5 on 2022-06-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_brand_category_customer_product_wishlist_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='customer',
            name='fav_brands',
            field=models.ManyToManyField(blank=True, related_name='fav_brands', to='webstore.brand'),
        ),
        migrations.AddField(
            model_name='customer',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to='webstore.product'),
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
