# Generated by Django 4.0.5 on 2022-06-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_remove_wishlist_customer_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fav_brands',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.product')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.brand')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.customer')),
            ],
        ),
    ]
