# Generated by Django 4.0.5 on 2022-06-14 12:12

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0004_remove_customer_fav_brands_remove_customer_wishlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_no',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, unique=True),
        ),
    ]
