# Generated by Django 4.0.5 on 2022-06-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0007_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to='profile_picture'),
        ),
    ]
